language: node_js

node_js:
  - 8.9.4

branches:
  only:
  - master

before_install:
  - git config --global user.name "tcly861204"
  - git config --global user.email "356671808@qq.com"
  
install:
  - npm install

script:
  - npm run dev
  - npm run build
  
after_success:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "发布新系统"
  - git remote add origin https://github.com/tcly861204/fabu.git
  - git pull origin master --allow-unrelated-histories
  - git add .
  - git commit -m "发布系统"
  - git push orign master
  